In [35]:
import numpy as np

In [36]:
#one dimensional array
sales = [0, 5, 155, 0, 518, 0, 1827, 616, 317, 325]

sales_array = np.array(sales)
sales_array


array([   0,    5,  155,    0,  518,    0, 1827,  616,  317,  325])

In [54]:
print(f"ndim: {sales_array.ndim}")
print(f"shape: {sales_array.shape}")
print(f"size: {sales_array.size}")
print(f"dtype: {sales_array.dtype}")
print(f"ndim: {sales_array.ndim}")

ndim: 2
shape: (2, 5)
size: 10
dtype: int32
ndim: 2


In [55]:
#two dimensional array
sales = [0, 5, 155, 0, 518], [0, 1827, 616, 317, 325]

sales_array = np.array(sales)
sales_array


array([[   0,    5,  155,    0,  518],
       [   0, 1827,  616,  317,  325]])

In [56]:
print(f"ndim: {sales_array.ndim}")
print(f"shape: {sales_array.shape}")
print(f"size: {sales_array.size}")
print(f"dtype: {sales_array.dtype}")
print(f"ndim: {sales_array.ndim}")

ndim: 2
shape: (2, 5)
size: 10
dtype: int32
ndim: 2


In [57]:
#example one dimensional
array = np.array(range(5))
array

array([0, 1, 2, 3, 4])

In [58]:
#two dimensonal
array2d = np.array([range(5), range(5)])
array2d 

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [59]:
array2d.ndim , array2d.shape, array2d.dtype, array2d.size

(2, (2, 5), dtype('int32'), 10)

In [60]:
array.ndim , array.shape, array.dtype, array.size

(1, (5,), dtype('int32'), 5)

In [61]:
np.array(['i', 'love', 'python'])

array(['i', 'love', 'python'], dtype='<U6')

In [62]:
#array creation

In [63]:
#np.one((rows,col),dtype)

np.ones(4,int)

array([1, 1, 1, 1])

In [165]:
np.ones((2,3,3),dtype=int) + np.ones(3)

array([[[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]],

       [[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]]])

In [65]:
#np.arange(start,stop,step)

np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
#stop is exclusive
np.arange(1,10,2)
np.arange(1,12,3)


array([ 1,  4,  7, 10])

In [67]:
#np.linspace(start,stop,n) print one the n number of digits
#stop is inclusive

np.linspace(9,81,9)

array([ 9., 18., 27., 36., 45., 54., 63., 72., 81.])

In [68]:
#np.array.reshape(rows,col)

np.arange(1,9,2).reshape(2,2)

array([[1, 3],
       [5, 7]])

In [69]:
np.zeros((6,20),int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [70]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [71]:
rng = np.random.default_rng(616)
rng.random(1)

array([0.39682145])

In [72]:
rng.integers(0,10,100)

array([9, 8, 4, 4, 4, 3, 1, 5, 6, 0, 1, 8, 0, 7, 3, 7, 9, 5, 8, 3, 6, 0,
       3, 3, 1, 2, 2, 4, 9, 1, 2, 5, 1, 8, 9, 0, 3, 1, 5, 8, 0, 6, 1, 7,
       0, 7, 6, 0, 3, 7, 1, 9, 4, 1, 6, 1, 4, 4, 9, 5, 3, 4, 7, 8, 3, 3,
       5, 0, 4, 9, 9, 5, 6, 5, 8, 2, 3, 0, 0, 8, 3, 8, 4, 8, 8, 9, 7, 3,
       8, 4, 9, 2, 6, 3, 0, 3, 2, 0, 0, 4], dtype=int64)

In [73]:
rng.normal(50,5,10).reshape(5,2)

array([[43.66324209, 51.53596392],
       [47.70105975, 48.70709975],
       [58.79869416, 47.36546164],
       [50.41694017, 47.18838872],
       [50.68654664, 53.53115044]])

In [74]:
#indexing and slicing one dimensional array
integer_array = np.arange(1,13)
integer_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [75]:
integer_array[1]


2

In [76]:
integer_array[-1]

12

In [77]:
integer_array[:5]

array([1, 2, 3, 4, 5])

In [78]:
integer_array[2:5]

array([3, 4, 5])

In [79]:
integer_array[1:10:2]

array([ 2,  4,  6,  8, 10])

In [80]:
integer_array[1::2]

array([ 2,  4,  6,  8, 10, 12])

In [81]:
integer_array[:5:2]

array([1, 3, 5])

In [82]:
integer_array[5:]

array([ 6,  7,  8,  9, 10, 11, 12])

In [83]:
integer_array[:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [84]:
#indexing and slicing two dimesional array
new_array = integer_array.reshape(3,4)

new_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [140]:
new_array[:,1]

array([ 2,  6, 10])

In [85]:
new_array[:,:]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [86]:
new_array[:1,:]

array([[1, 2, 3, 4]])

In [87]:
new_array[:,3:]

array([[ 4],
       [ 8],
       [12]])

In [88]:
new_array[1:2,:]

array([[5, 6, 7, 8]])

In [89]:
new_array[:,2]

array([ 3,  7, 11])

In [90]:
new_array[1:3,:]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [91]:
new_array[0:3:2,:]

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [92]:
new_array[:,0:3:2]

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])

In [93]:
new_array[2,1]

10

In [94]:
#arithematic operators
rng = np.random.default_rng(616)
inventory = rng.integers(0,100,10)
inventory 

array([39, 39, 93, 86, 48, 46, 48, 30, 11, 57], dtype=int64)

In [95]:
inventory - 24

array([ 15,  15,  69,  62,  24,  22,  24,   6, -13,  33], dtype=int64)

In [96]:
inventory/2

array([19.5, 19.5, 46.5, 43. , 24. , 23. , 24. , 15. ,  5.5, 28.5])

In [97]:
price = (rng.random(10) * 10).round(2)
price

array([0.89, 8.82, 7.32, 7.32, 5.62, 3.4 , 0.63, 3.57, 2.03, 4.31])

In [98]:
(price*inventory).sum()

2520.4700000000003

In [99]:
inventory_list = list(inventory)
inventory_list

[39, 39, 93, 86, 48, 46, 48, 30, 11, 57]

In [100]:
my_array = np.arange(20)
my_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [170]:
#filtering arrays 
sales_array = np.arange(5)
sales_array

array([0, 1, 2, 3, 4])

In [172]:
product_array = ['fruits','vegetables','cereal', 'dairy', 'eggs']
product_array = np.array(product_array)

In [178]:
product_array[sales_array>2]

array(['dairy', 'eggs'], dtype='<U10')

In [101]:

my_array % 2 ==0


array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False])

In [102]:
my_array[my_array % 2 ==0]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [103]:
even_odd = np.array(['even','odd']*10)
even_odd

array(['even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even',
       'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd',
       'even', 'odd'], dtype='<U4')

In [104]:
even_odd != 'odd'

array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False])

In [105]:
even_odd[even_odd != 'odd']

array(['even', 'even', 'even', 'even', 'even', 'even', 'even', 'even',
       'even', 'even'], dtype='<U4')

In [106]:
my_array[even_odd=='even'] = 0
my_array

array([ 0,  1,  0,  3,  0,  5,  0,  7,  0,  9,  0, 11,  0, 13,  0, 15,  0,
       17,  0, 19])

In [107]:
my_array[2] = 2
my_array

array([ 0,  1,  2,  3,  0,  5,  0,  7,  0,  9,  0, 11,  0, 13,  0, 15,  0,
       17,  0, 19])

In [108]:
my_array


array([ 0,  1,  2,  3,  0,  5,  0,  7,  0,  9,  0, 11,  0, 13,  0, 15,  0,
       17,  0, 19])

In [109]:
#where function
np.where(my_array%2==0,'even', 'odd')

array(['even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even',
       'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd',
       'even', 'odd'], dtype='<U4')

In [110]:
np.where(my_array%2==0,'even', my_array)

array(['even', '1', 'even', '3', 'even', '5', 'even', '7', 'even', '9',
       'even', '11', 'even', '13', 'even', '15', 'even', '17', 'even',
       '19'], dtype='<U11')

In [111]:
#array aggregation function
my_array.sum()

102

In [112]:
np.where(my_array%2==0,'even', np.where(my_array==9,my_array,'odd'))

array(['even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even',
       '9', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd',
       'even', 'odd'], dtype='<U11')

In [113]:
rng=np.random.default_rng(616)
price = (rng.random(10)*10).round(2)
price

array([3.97, 8.66, 4.6 , 3.06, 5.74, 0.89, 8.82, 7.32, 7.32, 5.62])

In [114]:
inventory = rng.integers(0,100,10)
inventory

array([80, 33, 60,  6, 31, 35, 16, 20, 29, 43], dtype=int64)

In [115]:
(price*inventory).sum()

1848.2900000000002

In [116]:
(price*inventory).mean()

184.829

In [117]:
my_array.mean()

5.1

In [118]:
my_array.max()

19

In [119]:
my_array.min()

0

In [120]:
#we can also aggreagate across rows and columns
price_2d = price.reshape(5,2)

In [121]:
price_2d

array([[3.97, 8.66],
       [4.6 , 3.06],
       [5.74, 0.89],
       [8.82, 7.32],
       [7.32, 5.62]])

In [122]:
#sum along coloum
price_2d.sum(axis=0)

array([30.45, 25.55])

In [123]:
#sum along rows
price_2d.sum(axis=1)

array([12.63,  7.66,  6.63, 16.14, 12.94])

In [124]:
price_2d.mean(axis=0)

array([6.09, 5.11])

In [125]:
#array function
product_value = (price*inventory)
product_value

array([317.6 , 285.78, 276.  ,  18.36, 177.94,  31.15, 141.12, 146.4 ,
       212.28, 241.66])

In [126]:
reshape_product_value = product_value.reshape(2,5)

In [127]:
np.median(reshape_product_value)

195.11

In [128]:
np.percentile(reshape_product_value,50)

195.11

In [129]:
np.sqrt(reshape_product_value)

array([[17.82133553, 16.90502884, 16.61324773,  4.28485706, 13.33941528],
       [ 5.5812185 , 11.87939392, 12.09958677, 14.56983185, 15.54541733]])

In [130]:
np.unique(reshape_product_value)   

array([ 18.36,  31.15, 141.12, 146.4 , 177.94, 212.28, 241.66, 276.  ,
       285.78, 317.6 ])

In [131]:
#sorting array
product_value


array([317.6 , 285.78, 276.  ,  18.36, 177.94,  31.15, 141.12, 146.4 ,
       212.28, 241.66])

In [132]:
np.sort(product_value)

array([ 18.36,  31.15, 141.12, 146.4 , 177.94, 212.28, 241.66, 276.  ,
       285.78, 317.6 ])

In [133]:
  product_value.sort()

In [134]:
product_value.max()

317.6

In [135]:
product_value[::-1]

array([317.6 , 285.78, 276.  , 241.66, 212.28, 177.94, 146.4 , 141.12,
        31.15,  18.36])